### ISSUE TITLE
这个该怎么添加下拉刷新呢？

### ISSUE THREAD

**Issue by Liuhuan247** [Roylee-ML/SwipeTableView#1]
这个该怎么添加下拉刷新呢？很纠结啊。好像很难啊

**Comment by Roylee-ML** [comment]
这个的实现原理是改变tableview的contentInsert的top值。而现在普遍使用的MJ等都是基于contentsize的，就是总是显示在content内容的顶部。所以添加下拉刷新后是隐藏在第一行cell顶部的。

解决的办法有两个：
1.自定义修改一个下拉刷新控件，使下拉刷新控件的header的frame不是显示在第一行cell的顶部，而是把tableView顶部contentInset的top值计算在呢，就是让下拉刷新的header显示在contentInset的top值之上。

2.由于为了兼容是每个tableView也能添加tableHeaderView，所以采用顶部添加contentInset的方式留出顶部的头视图空白。如果为了兼容常用的下拉刷新控件，像半糖采用的方式，可以修改源码如下：
①.在- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath方法中，给返回的重用的UIScrollView改为UITableView，并添加一个透明的tableHeaderView，frame的高正好是原代码中contentInset的top值。最后项目中所有的UIScrollView修改为UITableView（此时只能支持UITableView）。这样每个tableView的content内容便是从tableHeaderView开始的，像MJ等下拉刷新控件就能正常显示了。代码如下：

    UITableView * subView = cell.scrollView;
    if (_dataSource && [_dataSource respondsToSelector:@selector(swipeTableView:viewForItemAtIndex:reusingView:)]) {
        UITableView * newSubView = [_dataSource swipeTableView:self viewForItemAtIndex:indexPath.row reusingView:subView];
        // top inset
        CGFloat headerHeight = _headerInset + _barInset;
        UIEdgeInsets contentInset = newSubView.contentInset;
        contentInset.top = _swipeHeaderTopInset;
        newSubView.contentInset = contentInset;
        // header view
        UIView * headerView = [newSubView viewWithTag:666];
        if (nil == headerView) {
            headerView = [[UIView alloc]init];
            headerView.width = newSubView.width;
            headerView.tag = 666;
        }
        BOOL setHeaderHeight = [objc_getAssociatedObject(newSubView, SwipeTableViewItemTopInsetKey) boolValue];
        if (!setHeaderHeight) {
            headerView.height += headerHeight;
            objc_setAssociatedObject(newSubView, SwipeTableViewItemTopInsetKey, @(YES), OBJC_ASSOCIATION_RETAIN_NONATOMIC);
        }else {
            // update
            CGFloat deltHeaderHeight = headerHeight - headerView.height;
            headerView.height += deltHeaderHeight;
        }
        contentInset.top = headerView.height;
        newSubView.scrollIndicatorInsets = contentInset;
        newSubView.tableHeaderView = headerView;
        if (newSubView != subView) {
            [subView removeFromSuperview];
            [cell addSubview:newSubView];
            subView = newSubView;
        }
    }
②.修改- (void)adjustItemViewContentOffset:(UIScrollView *)itemView atIndex:(NSInteger)index fromLastItemView:(UIScrollView *)lastItemView lastIndex:(NSInteger)lastIndex中代码，代码如下：

    .....
    // 取出记录的offset
    // CGFloat topMarginOffsetY  = - (_swipeHeaderTopInset + _barInset);
    CGFloat topMarginOffsetY  = _headerInset - _swipeHeaderTopInset;
    NSValue *offsetObj = [self.contentOffsetQuene objectForKey:@(index)];
    CGPoint itemContentOffset = [offsetObj CGPointValue];
    if (nil == offsetObj) {  // init
        itemContentOffset.y = topMarginOffsetY;
    }
    .....
③.修改- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSString *,id> *)change context:(void *)context中代码，代码如下：

    if (!_swipeHeaderBarScrollDisabled) {
         CGFloat newOffsetY        = [change[NSKeyValueChangeNewKey] CGPointValue].y;
         CGFloat topMarginOffset   = _headerInset - _swipeHeaderTopInset;
         UIView * headerTopView    = _swipeHeaderView?_swipeHeaderView:_swipeHeaderBar;
            
         headerTopView.top = - newOffsetY;
         if (newOffsetY > topMarginOffset) {
             _swipeHeaderBar.top = _swipeHeaderTopInset;
         }else {
              if (_swipeHeaderView) {
                  _swipeHeaderBar.top = _swipeHeaderView.bottom;
              }
         }
    }

**Comment by wqhiOS** [comment]
那个第③布中的_swipeHeaderBarScrollDisabled 是哪里来的啊？？？

**Comment by Roylee-ML** [comment]
那个主要是为了在没有header的情况下，可以当做新闻类APP首页那样滑动item来用，设置这个后，bar就是悬停在顶部位置不变了。
而现在，在最新的版本中，只需要设置一个宏就可以支持下拉刷新了

**Comment by wqhiOS** [comment]
作者啊。。我试了下你最新的可以下拉刷新的版本，如果把shouldAdjustContentSize设置为NO没有什么问题，，但是如果我把shouldAdjustContentSize设置为YES，下拉刷新会出现问题，就是第一个Cell的下拉刷新是正常的，然后后面的那些cell 的下拉刷新就不能正常使用了。。你看下是怎么回事哈==（我这边是既想把shouldAdjustContentSize设置为YES，又想加入下拉刷新）。。。

**Comment by Roylee-ML** [comment]
你这里说的 cell 就是指的数据源中返回的 view 吧?还有,你说的其他的 cell 的下拉刷新不能正常使用,你能具体说下是怎么不正常的吗?我这边好重现一下问题,以便解决.

**Comment by wqhiOS** [comment]
抱歉哈，我刚说的cell 其实是- (UIScrollView *)swipeTableView:(SwipeTableView *)swipeView viewForItemAtIndex:(NSInteger)index reusingView:(UIScrollView *)view这个方法中返回的UIScrollView，我在这里返回的是tableView，然后我在每个tableView中都加上MJ的下拉刷新和上拉加载。如果我把shouldAdjustContentSize设置为NO，MJRefresh不会有问题，唯一的问题就是，比如我的第一个tableVIew中有很多数据，我一直刷到最下面，然后滑到第二个没有数据的tableView上的时候，第二个tableView的mj_footer会露出来。。所以为了解决这个问题，我把shoulAdjustContentSize设置为了YES，但是设置为YES之后遇到的问题就是，第一次执行下拉刷新没问题，然后滑到其他TableView执行下拉刷新就有问题，问题就是，我下拉刷新，然后还没有等到执行[self.tableView.mj_header endRefreshing]的时候tableView就立马停止刷新状态了（简单点说就是我对tableView做下拉刷新这个操作，然后tableView立马回到原来的位置。。。）。。作者，你要是还不明白的话给我个邮箱 我做个gif发给你==。。

**Comment by Roylee-ML** [comment]
你好,我重现了一下 bug. 也许是你想要的问题.现在解决办法如下:
   
 if (!_swipeHeaderBarScrollDisabled) {
        CGFloat newOffsetY        = [change[NSKeyValueChangeNewKey] CGPointValue].y;
        NSLog(@"kvo  frame == %f",self.swipeHeaderView.frame.origin.y);
        NSLog(@"offset ==== %f",newOffsetY);
    #if !defined(ST_PULLTOREFRESH_HEADER_HEIGHT)
        CGFloat initialOffsetY    = - (_swipeHeaderTopInset + _headerInset + _barInset);
        CGFloat topMarginInset    = _swipeHeaderTopInset + _barInset;
        UIView * headerBottomView = _swipeHeaderBar?_swipeHeaderBar:_swipeHeaderView;
            
        if (newOffsetY < - topMarginInset) {
            headerBottomView.bottom = fabs(newOffsetY);
        }else {
            headerBottomView.bottom = topMarginInset;
        }
        if (_swipeHeaderBar) {
            _swipeHeaderView.bottom = _swipeHeaderBar.top;
        }
    #else
        CGFloat initialOffsetY    = - _swipeHeaderTopInset;
        CGFloat topMarginOffset   = _headerInset - _swipeHeaderTopInset;
        UIView * headerTopView    = _swipeHeaderView?_swipeHeaderView:_swipeHeaderBar;
            
        headerTopView.top = - newOffsetY;
        if (newOffsetY > topMarginOffset) {
            _swipeHeaderBar.top = _swipeHeaderTopInset;
        }else {
            if (_swipeHeaderView) {
                _swipeHeaderBar.top = _swipeHeaderView.bottom;
            }
        }
    #endif
        if (newOffsetY < initialOffsetY) {
            [_contentOffsetQuene removeObjectForKey:@(self.currentItemIndex)];
        }
    }

这里做了一个判断,移除缓存记录的 offset

**Comment by wqhiOS** [comment]
作者，按你说的改了之后下拉刷新确实没有问题了。但是shouldAdjustContentSize=YES，貌似没有作用了，你再看下什么原因，辛苦了！

**Comment by Roylee-ML** [comment]
我在demo中测试了并没发现问题。你能把你的问题演示一下发给我吗？我明天再看一下。发自网易邮箱大师
            在2016年07月01日 00:52，wuqihan 写道:作者，按你说的改了之后下拉刷新确实没有问题了。但是shouldAdjustContentSize=YES，貌似没有作用了，你再看下什么原因，辛苦了！

**Comment by wqhiOS** [comment]
我把出现我说的问题的demo演示发到你的这个邮箱上了roylee.stillway@gmail.com。你明天有空看下， 多谢了！

**Comment by Roylee-ML** [comment]
你好,看了你的演示 demo 了,你提到的问题是底部的 footer 会露出来一部分.
非常抱歉,这个问题已经修改,只是目前还在完善一个新的功能,一直没有提交.新的版本马上就可以提交了,目前在你的这个版本中你可以在- (void)adjustItemViewContentOffset:(UIScrollView *)itemView atIndex:(NSInteger)index fromLastItemView:(UIScrollView *)lastItemView lastIndex:(NSInteger)lastIndex方法中修改如下代码:

        // adjust contentsize
        CGFloat contentHeight        = itemView.height + itemContentOffset.y;    // scrollview内容的高度
    #if !defined(ST_PULLTOREFRESH_HEADER_HEIGHT)
        CGFloat maxVisibleRectHeight = itemView.height - (_swipeHeaderTopInset + _barInset);  // 显示屏幕    的最大高度
    #else
        CGFloat maxVisibleRectHeight = itemView.height - _swipeHeaderTopInset + _headerInset;  // 显示屏幕的最大高度
    #endif
        CGFloat minRequireHeight     = _adaptMinContentSizeForBounds?  maxVisibleRectHeight:MIN(maxVisibleRectHeight, contentHeight);     // 最小要求的contentsize的高度
        minRequireHeight            -= itemView.contentInset.bottom;   // 修正contentInset的bottom的影响
        itemContentSize.height       = MAX(minRequireHeight, itemContentSize.height);  // 重设contentsize的高度

**Comment by wqhiOS** [comment]
完美！问题全部解决了。。期待你的下一个版本！

**Comment by Liuhuan247** [comment]
很棒，我的也搞定了。
