### ISSUE TITLE
MJRefresh上拉加载更多 偏移量问题

### ISSUE THREAD

**Issue by miniLV** [Roylee-ML/SwipeTableView#126]
当mj_footer开启上拉刷新，并请求完数据之后 - 一进入该tableVIew，tableView会自动上移，并进入`MJRefreshStatePulling`的状态，并且对该tableView设置 `state` 或者 `[self.mj_footer endRefreshing];`都无法改变 该tableView的状态，效果图如下：
![image](https://user-images.githubusercontent.com/20677007/44828373-27cb6a80-ac4a-11e8-85b1-d782ae16408f.png)

**Comment by miniLV** [comment]
![image](https://user-images.githubusercontent.com/20677007/44828569-28b0cc00-ac4b-11e8-8aab-77f7f0d6b705.png)
tableView 的 contentOffset 如图，这是刚进入tableView的时候，就出现的(上拉加载更多1页多数据的时候)

**Comment by miniLV** [comment]
已解决-。-

**Comment by dslcoding** [comment]
你是怎么解决的
