### ISSUE TITLE
headView里面放一个collectionView之后 headerView无法滑动怎么解决？

### ISSUE THREAD

**Issue by jiabinxu** [Roylee-ML/SwipeTableView#2]

**Comment by Roylee-ML** [comment]
我不太清楚你的问题，能不能具体的描述你的情况。swipeHeaderView是自定义的view，你能具体描述你的问题吗？或者你可以把你的情况发送我的邮箱或QQ联系：roylee-stillway@163.com，roylee.stillway@gmail.com,QQ867599670

**Comment by Roylee-ML** [comment]
在最新的提交0.2版本中，已经采用UIKit Dynamics物理动画引擎解决。当由于第三方下拉刷新控件的实现原理各异，这种条件下暂不支持第三方下拉刷新。
