### ISSUE TITLE
reusingView为nil

### ISSUE THREAD

**Issue by meiyua0218sdo** [Roylee-ML/SwipeTableView#32]
加载过的collectionView再次返回reusingView为nil的可能原因是什么呢

**Comment by Roylee-ML** [comment]
没有遇到过这样的情况。能否看下你数据源代理怎么写的？另外，如果是iOS10，请保证使用的是最新的版本。

**Comment by meiyua0218sdo** [comment]
`- (NSInteger)numberOfItemsInSwipeTableView:(SwipeTableView *)swipeView {
    return self.recommendArray.count;
}
- (UIScrollView *)swipeTableView:(SwipeTableView *)swipeView viewForItemAtIndex:(NSInteger)index reusingView:(UIScrollView *)view {
    
    NXDiscoverCollectionView * collectionView = self.collectionView;
    id data = _dataDic[@(index)];
    [collectionView refreshWithData:data atIndex:index];
    view = self.collectionView;
    [self configRefreshHeaderForItem:view];
    
    return view;
}
`

**Comment by Roylee-ML** [comment]
你这里只用了一个collectionview，应该是导致有的item的view为nil的原因。重用的话，至少要有两个的（两个item同时显示的情况）。

**Comment by meiyua0218sdo** [comment]
collection的样式一样就不需要两个了哈，不过我在用手势滑动的时候有时候会跳一下，导致headerView直接被标题栏顶到屏幕外，标题栏呈悬浮状态。不知道是什么影响的

**Comment by Roylee-ML** [comment]
没有像你这样用过。不太清楚，一个view可以同时呈现在两个不同的superview上，即便是自动的做了引用计数增加。

**Comment by meiyua0218sdo** [comment]
如果collection的样式都是相同的应该怎么创建呢

**Comment by Roylee-ML** [comment]
如果你不是特意要用属性保留collectionview，以便在其他地方使用的话，完全可以

```objc
NXDiscoverCollectionView * collectionView = (NXDiscoverCollectionView *)view;
// 重用
if (nil == collectionView) {
     collectionView = [[NXDiscoverCollectionView alloc]initWithFrame:swipeView.bounds];
     // config collectionview
     ......
}
// refresh data
id data = _dataDic[@(index)];
[collectionView refreshWithData:data atIndex:index];

return collectionView;  
```

对于当前item的获取，也完全可以用`_swipeTableView.currentItemView`

**Comment by meiyua0218sdo** [comment]
好的 谢谢 我试试

**Comment by Roylee-ML** [comment]
恩，不客气
