### ISSUE TITLE
在xcode8上运行项目，切换滑动，会出现headerView不随着滑动

### ISSUE THREAD

**Issue by KboyHub** [Roylee-ML/SwipeTableView#33]

**Comment by Roylee-ML** [comment]
我这边并没有发现这个问题。你能详细的说下你的情况吗？还有，你的是最新的版本吧？

**Comment by KboyHub** [comment]
现在没问题了，^_^
 if ([_contentView respondsToSelector:@selector(setPrefetchingEnabled:)]) {
        _contentView.prefetchingEnabled = NO;
    }
找到原因了，是我把上边的代码注释掉了

**Comment by Roylee-ML** [comment]
OK
