### ISSUE TITLE
你好，请问前面有下划线的-(void)_tapHeader 方法什么时候才会调用呢？

### ISSUE THREAD

**Issue by RivenDarry** [Roylee-ML/SwipeTableView#48]
STViewController的line：169，这里面有两个tapHeader方法，一个加了下划线，但是好像并没有代码去调用，这个是一个特殊的写法吗？在什么情况下会触发？

**Comment by Roylee-ML** [comment]
这个不是特殊写法。这是我的 demo 中做的 A\B 两种测试效果。你可以在图片 header的点击手势中把 action 替换为`_tapHeader`查看下效果
