### ISSUE TITLE
添加上拉加载

### ISSUE THREAD

**Issue by CoderJackie** [Roylee-ML/SwipeTableView#5]
一共4个item，要给第三个和第四个添加上拉加载，要怎么添加啊

**Comment by Roylee-ML** [comment]
如果你的item不重用的话，你直接在3，4个添加就行。如果采用的是相同的布局的item，使用了重用。你需要在数据源创建item之后的方法中根据index去设置你的refresh footer
例如：

    - (UIScrollView *)swipeTableView:(SwipeTableView *)swipeView viewForItemAtIndex:(NSInteger)index reusingView:(UIScrollView *)view {
       MyTableView * tableView = view;
       // lazy load
       if (nil == tableView) {
            MyTableView * tableView =  [[MyTableView alloc]initWithFrame:swipeView.bounds style:UITableViewStylePlain];
            tableView.backgroundColor = [UIColor whiteColor];
            // config the tableview
            .....
       }
       [tableView setData:dataArray];
       // do something 
       .....
       // your refresh footer
       if (index == YourRefreshIndex) {
          tableView.refreshFooter = .......;          
       }else {
          tableView.refreshFooter = nil;
       }
       return tableView;
    }
实现的大致逻辑可以参考这个，实际情况根据自己的项目略做调整

**Comment by CoderJackie** [comment]
没有复用，是在创建item时设置footer？

```
- (ThirdTableView *)thirdTableView
{
    if (!_thirdTableView) {
        _thirdTableView = [[ThirdTableView alloc] initWithFrame:self.swipeTableView.bounds];
        _thirdTableView.footer = [MJRefreshAutoFooter footerWithRefreshingBlock:^{
            NSLog(@"上拉加载");
        }];
    }
    return _thirdTableView;
}

```

```
- (UIScrollView *)swipeTableView:(SwipeTableView *)swipeView viewForItemAtIndex:(NSInteger)index reusingView:(UIScrollView *)view {
    if (index == 0) {
        view = self.firstTableView;
        [view performSelector:@selector(reloadData)];
    } else if (index == 1) {
        view = self.secondScrollView;
    } else if (index == 2) {
        view = self.thirdTableView;
        
        [view performSelector:@selector(reloadData)];
    }
    
    return view;
}
```

**Comment by Roylee-ML** [comment]
恩，没有复用的话，在你自己的item中（或者创建你自己的item的时候）设置footer就行。

**Comment by CoderJackie** [comment]
试过了，上拉加载，看不见footer，用不用额外设置什么属性？

**Comment by CoderJackie** [comment]
而且只能加载出来一次数据，第二次继续上拉，不会调用block，滚动条也是异常的

![simulator screen shot 2016 7 5 11 17 54](https://cloud.githubusercontent.com/assets/3355958/16573056/2b8f7850-42a2-11e6-9c7f-9a90e726d89f.png)

**Comment by Roylee-ML** [comment]
很抱歉，我不是很明白你的问题。你能否把你的这个demo发送到我的邮箱，然后我看一下问题吗？

2016-07-05 11:18 GMT+08:00 CoderJackie <notifications@github.com>:

**Comment by CoderJackie** [comment]
你邮箱或者QQ是多少，我加你

**Comment by Roylee-ML** [comment]
roylee.stillway@gmail.com,roylee-stillway@163.com

2016-07-05 13:47 GMT+08:00 CoderJackie <notifications@github.com>:
