### ISSUE TITLE
你好,请问这个展示功能的图片是利用什么工具制作的呢?

### ISSUE THREAD

**Issue by jniosdeveloper** [Roylee-ML/SwipeTableView#60]
希望能够告知这个功能展示的动态图片是使用啥工具制作的,非常感谢

**Comment by laznrbfe** [comment]
I think this app is licecap.

**Comment by Roylee-ML** [comment]
没用软件，直接代码生成的。 软件的话，有个[LICEcap](https://github.com/justinfrankel/licecap)可以用
