### ISSUE TITLE
使用MJRefresh时，header初始化时就显示的问题

### ISSUE THREAD

**Issue by elementuse** [Roylee-ML/SwipeTableView#65]
非常感谢您提供这个有用的控件，我在使用时遇到一个问题，使用的是MJRefresh作为刷新控件，在加入底部TabBarControl导航控件时，MJRefresh的头部视图在初始化时就显示，这个问题困扰了我很久，不知道什么原因，请求你帮助
<img width="311" alt="error" src="https://cloud.githubusercontent.com/assets/5210594/26626702/aed6f5c6-462a-11e7-8c3f-cfddc6c556c2.png">

**Comment by elementuse** [comment]
[SwipeTableView.zip](https://github.com/Roylee-ML/SwipeTableView/files/1040993/SwipeTableView.zip)
这是我修改的项目文件，主要加了MJRefresh，以及调整Storyboard的显示方式
另外#define ST_PULLTOREFRESH_HEADER_HEIGHT  MJRefreshHeaderHeight已设置

**Comment by Roylee-ML** [comment]
这个是 viewcontroller 的 view 的 frame 变化导致的问题。可以通过`SwipeTableView`的属性`swipeHeaderTopInset`，设置为`0`之后，调整顶部悬停的位置。另外，对于控件`SwipeTableView`的`frame`设置，如果可以的话，初始化的时候最好可以设置固定的已知数值，demo 中的`autoresizingMask`设置也要去掉，因为`SwipeTableView`并没有对 autolayout 做很好的支持。

**Comment by elementuse** [comment]
试了可以，谢谢
