### ISSUE TITLE
请问楼主，为什么tableView的这个方法不执行了？-(CGFloat)tableView: heightForHeaderInSection:

### ISSUE THREAD

**Issue by huangxuhui7** [Roylee-ML/SwipeTableView#69]

**Comment by Roylee-ML** [comment]
这个应该跟`SwipeTableView`没有什么关系。建议检查下 tableview 的代理的设置。

另外，如果你的 tableview 的 style 是 plain 模式，需要设置`SwipeTableView`下拉刷新宏，否则 tableview 的`contentInset`会影响 section header 位置的显示；或者采用 tableview 的 group 模式。
