### ISSUE TITLE
0.2.3 version is not on cocoa pod 

### ISSUE THREAD

**Issue by xtreme8210** [Roylee-ML/SwipeTableView#7]
Hi Roylee,
is it possible to put the newest version onto cocoapod?
thanks

**Comment by Roylee-ML** [comment]
It is possible,please try again. You can use `pod search SwipeTableView` to check the versions.
If you have used cocapod to install `SwipeTableView` before,you can try `pod update SwipeTableView` to update it.

**Comment by xtreme8210** [comment]
Hi Roylee,

I can only find version 0.1.1 with pod search, but it doesn't match with cocoa pod website's version (0.2.3)
![2016-07-07 9 22 48](https://cloud.githubusercontent.com/assets/2245528/16639751/0c9f0f4e-4425-11e6-9255-805a5ae25697.png)
![2016-07-07 9 23 22](https://cloud.githubusercontent.com/assets/2245528/16639753/149ed44a-4425-11e6-843f-dbf276dc683d.png)
![2016-07-07 9 25 29](https://cloud.githubusercontent.com/assets/2245528/16639754/14e68b1e-4425-11e6-9304-d77e62ee3484.png)

**Comment by Roylee-ML** [comment]
You can use the command below to fix it:

    $rm -fr ~/.cocoapods/repos/master
    $pod setup

**Comment by xtreme8210** [comment]
Hi Roylee,
I just type $pod setup and worked!
I now can pod search and see the 0.2.3 version.
thank you very much :)
