### ISSUE TITLE
bar的样式 

### ISSUE THREAD

**Issue by zzdota** [Roylee-ML/SwipeTableView#74]
demo里面bar的样式太普通了,
能多提供几种常用的么,  比喻下划线的,小箭头的,椭圆形的背景等~~
或者bar能让使用者自定义

**Comment by Roylee-ML** [comment]
demo 中的 bar 与 refresh 等都是为了实现当前项目的功能效果，而这些并不是这个项目中所要体现的东西。bar 那种的，github 上有很多开源（比如[HMSegmentedControl](https://github.com/HeshamMegid/HMSegmentedControl)），可以自行选择。
