### ISSUE TITLE
Item 下拉刷新中，切换视图，位置不对

### ISSUE THREAD

**Issue by Homin818** [Roylee-ML/SwipeTableView#77]
假设SwipeTableView 里面有三个item，当其中一个执行下拉刷新，此时左右切换到另外一个Other Item，这时候Other Item 就会显示下拉刷新的控件(闲置状态)。

**Comment by Roylee-ML** [comment]
这个在2.x 版本中会存在的情况，下拉刷新属于外部因素，SwipeTableView 并不考虑，所以相邻两个 item 仍然是对齐的状态。

不过，在 [3.0](https://github.com/Roylee-ML/SwipeTableView/tree/3.0)分支中，已经默认对 contentInset 的初始值做了保留，因此在橫滑之后，会忽略之前下拉的间隙保证另一个 item 是正常的位置。
