### ISSUE TITLE
STCollectionView上加一个筛选条

### ISSUE THREAD

**Issue by billlk123** [Roylee-ML/SwipeTableView#82]
![wechatimg2](https://user-images.githubusercontent.com/12571530/29909648-786dfd64-8e59-11e7-9833-a9cc970af955.jpeg)
上面这种，在其中一个STCollectionView上加个筛选条。这个筛选条也一直悬停在顶部，应该怎么写？

**Comment by Roylee-ML** [comment]
如果只是其中一个，不是所有都有这个筛选条的话，这个需要自己单独处理下。

这个筛选条可以放在当前collectionview的父视图上，然后对`SwipeTableView`的公共bar的frame进行监听（KVO 或者 RAC），始终让这个单独的筛选条跟随在公共bar的下面，另外如果坐标系不在一个图层可以做UIView的坐标转换。。。

**Comment by billlk123** [comment]
这个筛选条应该在哪个地方加到当前collectionview的父视图上？我都拿不到当前collectionview的父视图。我只能想到在didMoveToSuperview里加，但是SwipeTableView该怎么获取。我在当前collectionview上用self.swipeTableView拿不到，拿不到我该怎么监听

**Comment by billlk123** [comment]
解决了，在STCollectionView上设置内容偏移，流出筛选视图的位置，然后在didMoveToSuperview里添加筛选视图到STCollectionView的父视图上。在swipetableview的代理viewForItemAtIndex里面拿到swipetableview，监听swipetableview的bar。拿到bar的底部坐标，然后转换到STCollectionView的父视图上，然后改变筛选视图的frame
