### ISSUE TITLE
tableView底部留白问题

### ISSUE THREAD

**Issue by liuxu0718** [Roylee-ML/SwipeTableView#88]
无论是demo还是集成到项目里 详情页面的子tableView底部的留白总是有一块（当数据足够多，已经设置tableFooterView=[UIView new];）

**Comment by liuxu0718** [comment]
Type下的小tableView

**Comment by Roylee-ML** [comment]
能否提供更详细的信息或者截图

另外，如果你用的是 master 分支版本，可以试下3.0分支，目前主要维护这个分支

**Comment by liuxu0718** [comment]
- (void)getDataAtIndex:(NSInteger)index {
    if (nil != _dataDic[@(index)]) {
        return;
    }
    NSInteger numberOfRows = 20;
    // 请求数据后刷新相应的item
    ((void (*)(void *, SEL, NSNumber *, NSInteger))objc_msgSend)((__bridge void *)(self.swipeTableView.currentItemView),@selector(refreshWithData:atIndex:), @(numberOfRows),index);
    // 保存数据
    [_dataDic setObject:@(numberOfRows) forKey:@(index)];
}

最后排查是这个方法产生的留白，实际开发中这里做数据请求应该怎么去处理request？

**Comment by Roylee-ML** [comment]
这应该是个 bug，我排查一下

**Comment by liuxu0718** [comment]
这里是把numberOfRows 改成了一个数字 bug就没了，bug时的代码是这样的
// 请求数据（根据视图滚动到相应的index后再请求数据）
- (void)getDataAtIndex:(NSInteger)index {
    if (nil != _dataDic[@(index)]) {
        return;
    }
    NSInteger numberOfRows = 0;
    switch (index) {
        case 0:
            numberOfRows = 8;
            break;
        case 1:
            numberOfRows = 10;
            break;
        case 2:
            numberOfRows = 5;
            break;
        case 3:
            numberOfRows = 12;
            break;
        default:
            break;
    }
    // 请求数据后刷新相应的item
    ((void (*)(void *, SEL, NSNumber *, NSInteger))objc_msgSend)((__bridge void *)(self.swipeTableView.currentItemView),@selector(refreshWithData:atIndex:), @(numberOfRows),index);
    // 保存数据
    [_dataDic setObject:@(numberOfRows) forKey:@(index)];
}

另外还一个bug 您可以试试，
- (UIScrollView *)swipeTableView:(SwipeTableView *)swipeView viewForItemAtIndex:(NSInteger)index reusingView:(UIScrollView *)view { 
当这个方法里用不同的tableView对象作为返回值时（我最开始用的是demo种normal的那种写法，写的其他两个tableView的返回），点击sgementBar的item，切换发现异常，应该是重用的问题，而且只有点击的时候发生异常，滑动无异常。
后来我这里解决的方案是：我都用的懒加载去写的其他两个tableView 就没有异常了（CustomTableView * tableView = self.tableView这种写法）。

**Comment by liuxu0718** [comment]
这里我是改到需要的样子后，同时出现的这两个bug。

**Comment by Roylee-ML** [comment]
底部留白的问题，是设置属性 `shouldAdjustContentSize` 为 `YES` 的时候，会自动改变 `contentSize` 来适应屏幕最大滑动范围的

另外，由于 `SwipeTableView` 存在重用机制。所以，要按照重用的规则去处理 itemview，否则会出现一个 itemview 被相邻 index 利用后出现空白现象
