### ISSUE TITLE
关于监听 ContentOffset 的问题

### ISSUE THREAD

**Issue by didez** [Roylee-ML/SwipeTableView#92]
有交互需要监听 OffsetY, 目前通过监听 tableview 的 ContentOffset 实现

遇到问题: 左右滑动切换时, 会触发 OffsetY = 0 后还原, 导致逻辑错误

有更好的监听方式吗

**Comment by Roylee-ML** [comment]
不是很清楚你要解决的业务问题。

不过，看你是不是可以尝试一下不重用的方式。目前我们的项目中就是采用 controller 管理，并且不重用。在 swipetableview 所在的 controller 中懒加载保留所有的 controller（每个 controller 自己管理自己的内容警告），在代理中返回对应的 controller 的 view。

**Comment by didez** [comment]
感谢回答😀

**Comment by Heisenbean** [comment]
确实,监听tableview 的 ContentOffset,在左右滑动的时候回触发OffsetY = 0,LZ是怎样解决的
