### ISSUE TITLE
3.0 demo在iPhone X 模拟器上刷新之后都有偏差，能不能完善一下demo

### ISSUE THREAD

**Issue by UknowHui** [Roylee-ML/SwipeTableView#94]

**Comment by didez** [comment]
修复很简单的, 我这里兼容了

https://github.com/didez/SwipeTableView

**Comment by UknowHui** [comment]
<img width="433" alt="1" src="https://user-images.githubusercontent.com/13573509/32540118-a2170632-c4a6-11e7-839d-ab725df53840.png">

**Comment by Roylee-ML** [comment]
之前做了 iOS11的兼容，后来忘了怎么把代码注释后，一块跟着 readme 的修改提交了。现在做了重新编译处理
