### ISSUE TITLE
滑动了一下headerbar，点返回，就crash了

### ISSUE THREAD

**Issue by DanielYK** [Roylee-ML/SwipeTableView#97]
可能原因会有哪些呢 ？

**Comment by Roylee-ML** [comment]
能提供下崩溃的信息吗？

**Comment by DanielYK** [comment]
唯一的错误信息：*_cmd	SEL	<no value available>	0x024d4301024d43c0

crash在 @implementation SwipeTableView 这一行，其他没任何输出

**Comment by DanielYK** [comment]
*_cmd	SEL  	<no value available>	0x024d4301024d43c0

**Comment by DanielYK** [comment]
*_cmd	<no value available>	0x024d4301024d43c0

**Comment by DanielYK** [comment]
*_cmd	no value available   0x024d4301024d43c0

**Comment by Roylee-ML** [comment]
能不能提供下崩溃栈的信息？或者你开下exceptions断点看下崩溃

**Comment by DanielYK** [comment]
我抛弃了，用了其他的了。。。

**Comment by Roylee-ML** [comment]
好的

**Comment by ShaoXinSen** [comment]
@DanielYK 其他有类似的可以推荐吗?
